[package]
name = "rickroll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.11"
rand = "0.8.5"
webbrowser = "0.8.2"
